### ISSUE TITLE
Convert stereo recording to single channel

### ISSUE THREAD

**Issue by funboarder13920** [lhotse-speech/lhotse#1049] opened 2023-05-03 08:10 UTC
Hello,
Is there a way to convert a stereo recording to single channel ?

**Comment by desh2608** [comment] 2023-05-03 12:19
```python
from lhotse import Recording

# Read recording and convert to cut (MultiCut will be created by default)
c = Recording.from_file("/path/to/stereo.wav").to_cut()
# Convert to MonoCut; this will mix all tracks
m = c.to_mono()
# Save mixed audio
m.save_audio("/out/path.wav")
```

This is one way I can think of.

**Comment by pzelasko** [comment] 2023-05-03 15:53
Actually I think that `MultiCut.to_mono()` returns a list of mono cuts; if you want to mix them into mono you'll need to modify this example with sth like ```cut = m[0]; for other in m[1:]: cut = cut.mix(other); cut.save_audio(...)```. Maybe we should add an option whether to downmix or keep each channel separately.

**Comment by desh2608** [comment] 2023-05-03 16:02
Ahh, right. My bad! I was thinking of a `MixedCut`.

**Comment by AmirHussein96** [comment] 2023-05-22 15:36
This is an example prepared using old lhotse. The monocut has the same id as the supervision and the recording is the original recording.

```
MonoCut(id='fla_0225_0A_00021', start=31.56, duration=0.42, channel=0, supervisions=[SupervisionSegment(id='fla_0225_0A_00021', recording_id='fla_0225', start=0.0, duration=0.42, channel=0, text='تفضل', language=None, speaker='fla_0225_0A', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='fla_0225', sources=[AudioSource(type='file', channels=[0, 1], source='/alt-data/speech/asr_data/LDC/LDC2006S29/cts_lev_ara_td5_a_d1/data/02/fla_0225.sph')], sampling_rate=16000, num_samples=6406272, duration=400.392, channel_ids=[0, 1], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 8000, 'target_sampling_rate': 16000}}]), custom=None)
```

**Comment by desh2608** [comment] 2023-05-22 15:38
Creating a MultiCut for a multi-channel recording is by design. Earlier versions of Lhotse created MonoCuts for this because there was no concept of a MultiCut at the time. That part is not the problem.

The problem is in the trimming. If you do `trim_to_supervisions(keep_overlapping=False, keep_all_channels=False)`, you should get 1 MonoCut per supervision. Can you check this? It should not cause any AssertionError --- if it is throwing an AssertionError, we need to check why.

**Comment by AmirHussein96** [comment] 2023-05-22 16:15
Ok I tried it and it worked perfectly, @desh2608 thank you for your help.

**Comment by desh2608** [comment] 2023-05-22 16:35
Cool. I'm closing this issue as resolved.

**Closed by desh2608** 2023-05-22 16:35 UTC

**Comment by funboarder13920** [comment] 2023-05-24 07:32
Thank you @desh2608
