### ISSUE TITLE
snowfall crash when setting minibatch_size in decode.py to 64 instead of None

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#162] opened 2020-12-14 09:37 UTC
```
2020-12-14 17:34:45,003 INFO [common.py:43] load checkpoint from exp/epoch-2.pt
convert LG to device
About to decode
[New Thread 0x7fff0a81a700 (LWP 3832011)]

Traceback (most recent call last):
  File "decode.py", line 176, in <module>
    main()
  File "decode.py", line 150, in main
    results = decode(dataloader=test_dl,
  File "decode.py", line 29, in decode
    for batch_idx, batch in enumerate(dataloader):
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 35, in fetch
    return self.collate_fn(data)
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [46, 2960, 40] at entry 0 and [165, 3496, 40] at entry 1


```

**Comment by danpovey** [comment] 2020-12-14 09:39
Realized just now that the minibatches already exist at that point so batch_size=64 may not make sense, but prob. this error message is not how we want it to show up.

**Comment by qindazhu** [comment] 2020-12-14 09:45
yeah, BTW,  the batch_size is determined automatically for now, this is the original design of iterable dataset in lhotse.

https://github.com/lhotse-speech/lhotse/blob/a45a0c2c17671d0e39eadd8956d883a7cf07d8d4/lhotse/dataset/speech_recognition.py#L70-L73

**Comment by pzelasko** [comment] 2020-12-16 02:28
The problem is that this error is happening in the DataLoader's code which is a part of PyTorch (because you're setting the `batch_size` in its __init__). I'm not sure what can we do to improve the error message...

**Comment by pzelasko** [comment] 2020-12-22 01:27
@danpovey can we close this?

**Closed** 2020-12-22 03:13 UTC
Labels: discussion
